#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 15 22:39:54 2019

@author: reality
"""

import numpy as np
testArray = np.array([[11,5],[32,6],[3,7],[14,8]]);

testArray.sort(axis=1);
print(testArray)

"""
list1 = [3,2,4,1, 1]
list2 = ['three', 'two', 'four', 'one', 'one2']
list1, list2 = zip(*sorted(zip(list1, list2)))
"""
