#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 12 21:14:49 2019

@author: reality
"""

def make_folds(x, num_folds):
   if num_folds == 1: #base case
        return [np.asarray(x)];
    
    division = len(x) / num_folds; #number of elements per bin
    
    if len(x) % num_folds != 0:
        tempArray = []
        for i in range(0,num_folds):
            tempArray.append(np.asarray([x[i]]))
        return tempArray;
            
    holder = []
    tempHolder = []
    counter = 0;
    for index in x:
        tempHolder.append(index);
        counter = counter + 1; 
        if counter == division:
            holder.append(np.asarray(tempHolder));
            tempHolder = [];
            counter = 0;
    return holder;
    
make_folds([1,2,3,4,5,6], 3)