#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 15 23:18:34 2019

@author: reality
"""
import numpy as np

def poly_grad(coefs, x):
    
    total = float(0);
    
    x_degree = 0;
    
    for i in coefs:
        coefficient = x_degree*i;
        print("coefficient", coefficient)
        if x_degree != 0:
            newXcoefficient = x_degree -1;
        else:
            newXcoefficient = x_degree;
        print(newXcoefficient)
        newXValue = np.power(x,newXcoefficient);
        print("newXValue", newXValue)
        partialSum = coefficient * newXValue;
        total += partialSum;
        x_degree += 1;
    return total;
    print(total)
    
poly_grad((0, 2, 4), 2)